export const oneHandSword = [
  {
    id: 0,
    name: "Grim Fang (Short Sword)",
    img: "https://docs.median-xl.com/images/baseitems/invssd.jpg",
    info: [
      {
        tier: "Tier 1",
        damage: ["One-Hand Damage: (4 - 5) to 7"],
        requirement: ["Required Level: 12", "Item Level: 1", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "+(18 to 29)% Enhanced Damage",
          "(3 to 5)% Life stolen per Hit",
          "-3% to Enemy Poison Resistance",
          "+(1 to 3) to Plague (Paladin Only)",
          "+10 to Strength",
          "Poison Resist +(11 to 15)%",
          "Socketed (1)",
        ],
      },
      {
        tier: "Tier 2",
        damage: ["One-Hand Damage: (12 - 13) to (12 - 13)"],
        requirement: ["Required Level: 19", "Required Strength: 18", "Item Level: 21", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "+(41 to 52)% Enhanced Damage",
          "(9 to 11)% Life stolen per Hit",
          "-6% to Enemy Poison Resistance",
          "+(3 to 6) to Plague (Paladin Only)",
          "+20 to Strength",
          "Poison Resist +(21 to 25)%",
          "Socketed (2)",
        ],
      },
      {
        tier: "Tier 3",
        damage: ["One-Hand Damage: (22 - 24) to (24 - 26)"],
        requirement: ["Required Level: 37", "Required Strength: 49", "Item Level: 41", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "+(64 to 75)% Enhanced Damage",
          "(15 to 17)% Life stolen per Hit",
          "-9% to Enemy Poison Resistance",
          "+(7 to 12) to Plague (Paladin Only)",
          "+30 to Strength",
          "Poison Resist +(31 to 35)%",
          "Socketed (3)",
        ],
      },
      {
        tier: "Tier 4",
        damage: ["One-Hand Damage: (29 - 31) to (33 - 35)"],
        requirement: ["Required Level: 46", "Required Strength: 104", "Item Level: 73", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "+(75 to 86)% Enhanced Damage",
          "(18 to 20)% Life stolen per Hit",
          "-12% to Enemy Poison Resistance",
          "+(13 to 18) to Plague (Paladin Only)",
          "+40 to Strength",
          "Poison Resist +(36 to 40)%",
          "Socketed (3)",
        ],
      },
    ],
  },
  {
    id: 1,
    name: "Al Nath (Scimitar)",
    img: "https://docs.median-xl.com/images/baseitems/invscm.jpg",
    info: [
      {
        tier: "Tier 1",
        damage: ["One-Hand Damage: (6 - 7) to (18 - 29)"],
        requirement: ["Required Level: 2", "Required Strength: 25", "Item Level: 4", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "15% Attack Speed",
          "+(31 to 50)% Enhanced Damage",
          "+(11 to 20) to Maximum Damage",
          "(41 to 60)% Bonus to Attack Rating",
          "Adds (6 to 10)-(11 to 13) fire damage",
          "Slow Target (3 to 5)%",
          "(3 to 5)% to Strength",
          "Socketed (1)",
        ],
      },
      {
        tier: "Tier 2",
        damage: ["One-Hand Damage: (17 - 19) to (40 - 51)"],
        requirement: ["Required Level: 20", "Required Strength: 48", "Item Level: 22", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "25% Attack Speed",
          "+(61 to 80)% Enhanced Damage",
          "+(21 to 30) to Maximum Damage",
          "(71 to 90)% Bonus to Attack Rating",
          "Adds (16 to 20)-(31 to 35) fire damage",
          "Slow Target (9 to 11)%",
          "(9 to 11)% to Strength",
          "Socketed (2)",
        ],
      },
      {
        tier: "Tier 3",
        damage: ["One-Hand Damage: (32 - 35) to (67 - 79)"],
        requirement: ["Required Level: 39", "Required Strength: 104", "Item Level: 43", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "35% Attack Speed",
          "+(91 to 110)% Enhanced Damage",
          "+(31 to 40) to Maximum Damage",
          "(101 to 120)% Bonus to Attack Rating",
          "Adds (46 to 55)-(86 to 100) fire damage",
          "Slow Target (15 to 17)%",
          "(15 to 17)% to Strength",
          "Socketed (3)",
        ],
      },
      {
        tier: "Tier 4",
        damage: ["One-Hand Damage: (44 - 48) to (91 - 105)"],
        requirement: ["Required Level: 48", "Required Strength: 212", "Item Level: 76", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "50% Attack Speed",
          "+(121 to 140)% Enhanced Damage",
          "+(41 to 50) to Maximum Damage",
          "(131 to 150)% Bonus to Attack Rating",
          "Adds (121 to 160)-(261 to 300) fire damage",
          "Slow Target (18 to 20)%",
          "(18 to 20)% to Strength",
          "Socketed (3)",
        ],
      },
    ],
  },
  {
    id: 2,
    name: "Wardance (Saber)",
    img: "https://docs.median-xl.com/images/baseitems/invsbr.jpg",
    info: [
      {
        tier: "Tier 1",
        damage: ["One-Hand Damage: 6 to 8"],
        requirement: ["Required Level: 4", "Required Strength: 37", "Item Level: 6", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "(31 to 35)% Attack Speed",
          "(4 to 6)% Chance of Crushing Blow",
          "+(51 to 200) Defense vs. Missile",
          "Physical Resist 1%",
          "Total Character Defense 15%",
          "+2% to Experience Gained",
          "Socketed (1)",
        ],
      },
      {
        tier: "Tier 2",
        damage: ["One-Hand Damage: 13 to 14"],
        requirement: ["Required Level: 22", "Required Strength: 64", "Item Level: 25", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "30% Attack Speed",
          "(8 to 10)% Chance of Crushing Blow",
          "+(301 to 500) Defense vs. Missile",
          "Physical Resist 2%",
          "Total Character Defense 30%",
          "+3% to Experience Gained",
          "Socketed (2)",
        ],
      },
      {
        tier: "Tier 3",
        damage: ["One-Hand Damage: 20 to 23"],
        requirement: ["Required Level: 41", "Required Strength: 132", "Item Level: 45", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "45% Attack Speed",
          "(11 to 13)% Chance of Crushing Blow",
          "+(701 to 900) Defense vs. Missile",
          "Physical Resist 3%",
          "Total Character Defense 45%",
          "+4% to Experience Gained",
          "Socketed (3)",
        ],
      },
      {
        tier: "Tier 4",
        damage: ["One-Hand Damage: 23 to 27"],
        requirement: ["Required Level: 50", "Required Strength: 265", "Item Level: 79", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "60% Attack Speed",
          "(14 to 16)% Chance of Crushing Blow",
          "+(1001 to 1200) Defense vs. Missile",
          "Physical Resist 4%",
          "Total Character Defense 60%",
          "+5% to Experience Gained",
          "Socketed (3)",
        ],
      },
    ],
  },
  {
    id: 3,
    name: "Finis Terra (Falchion)",
    img: "https://docs.median-xl.com/images/baseitems/invflc.jpg",
    info: [
      {
        tier: "Tier 1",
        damage: ["One-Hand Damage: (9 - 11) to (11 - 12)"],
        requirement: ["Required Strength: 49", "Item Level: 8", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "3% Chance to cast level 2 Shower of Rocks on Melee Attack",
          "+(24 to 40)% Enhanced Damage",
          "Adds 10-16 fire damage",
          "Adds 10-16 lightning damage",
          "Adds 10-16 cold damage",
          "Fire Resist +(11 to 15)%",
          "Poison Resist +(11 to 15)%",
          "Socketed (1)",
        ],
      },
      {
        tier: "Tier 2",
        damage: ["One-Hand Damage: (22 - 24) to (26 - 29)"],
        requirement: ["Required Strength: 79", "Item Level: 27", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "7% Chance to cast level 6 Shower of Rocks on Melee Attack",
          "+(58 to 75)% Enhanced Damage",
          "Adds 30-50 fire damage",
          "Adds 30-50 lightning damage",
          "Adds 30-50 cold damage",
          "Fire Resist +(21 to 25)%",
          "Poison Resist +(21 to 25)%",
          "Socketed (2)",
        ],
      },
      {
        tier: "Tier 3",
        damage: ["One-Hand Damage: (42 - 45) to (49 - 54)"],
        requirement: ["Required Strength: 160", "Item Level: 47", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "11% Chance to cast level 10 Shower of Rocks on Melee Attack",
          "+(92 to 109)% Enhanced Damage",
          "Adds 90-150 fire damage",
          "Adds 90-150 lightning damage",
          "Adds 90-150 cold damage",
          "Fire Resist +(31 to 35)%",
          "Poison Resist +(31 to 35)%",
          "Socketed (3)",
        ],
      },
      {
        tier: "Tier 4",
        damage: ["One-Hand Damage: (54 - 58) to (64 - 70)"],
        requirement: ["Required Strength: 319", "Item Level: 82", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "13% Chance to cast level 12 Shower of Rocks on Melee Attack",
          "+(109 to 126)% Enhanced Damage",
          "Adds 280-440 fire damage",
          "Adds 280-440 lightning damage",
          "Adds 280-440 cold damage",
          "Fire Resist +(36 to 40)%",
          "Poison Resist +(36 to 40)%",
          "Socketed (3)",
        ],
      },
    ],
  },
  {
    id: 4,
    name: "Raptor Beak (Broad Sword)",
    img: "https://docs.median-xl.com/images/baseitems/invbsd.jpg",
    info: [
      {
        tier: "Tier 1",
        damage: ["One-Hand Damage: (12 - 14) to (25 - 27)"],
        requirement: ["Required Strength: 61", "Item Level: 10", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "20% Attack Speed",
          "+(41 to 60)% Enhanced Damage",
          "+10 to Maximum Damage",
          "+(11 to 15) to Vitality",
          "+1 Mana on Striking",
          "+(11 to 15) Life when Struck by an Enemy",
          "(4 to 7)% Gold Find",
          "Socketed (2)",
        ],
      },
      {
        tier: "Tier 2",
        damage: ["One-Hand Damage: (27 - 30) to (52 - 56)"],
        requirement: ["Required Strength: 95", "Item Level: 27", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "30% Attack Speed",
          "+(71 to 90)% Enhanced Damage",
          "+20 to Maximum Damage",
          "+(21 to 25) to Vitality",
          "+1 Mana on Striking",
          "+(21 to 40) Life when Struck by an Enemy",
          "(9 to 12)% Gold Find",
          "Socketed (4)",
        ],
      },
      {
        tier: "Tier 3",
        damage: ["One-Hand Damage: (50 - 55) to (88 - 93)"],
        requirement: ["Required Strength: 188", "Item Level: 49", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "40% Attack Speed",
          "+(101 to 120)% Enhanced Damage",
          "+30 to Maximum Damage",
          "+(31 to 35) to Vitality",
          "+2 Mana on Striking",
          "+(51 to 70) Life when Struck by an Enemy",
          "(14 to 17)% Gold Find",
          "Socketed (5)",
        ],
      },
      {
        tier: "Tier 4",
        damage: ["One-Hand Damage: (66 - 72) to (120 - 127)"],
        requirement: ["Required Strength: 373", "Item Level: 84", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "50% Attack Speed",
          "+(131 to 150)% Enhanced Damage",
          "+40 to Maximum Damage",
          "+(36 to 40) to Vitality",
          "+2 Mana on Striking",
          "+(81 to 100) Life when Struck by an Enemy",
          "(17 to 19)% Gold Find",
          "Socketed (6)",
        ],
      },
    ],
  },
  {
    id: 5,
    name: "Herr Donner (Long Sword)",
    img: "https://docs.median-xl.com/images/baseitems/invlsd.jpg",
    info: [
      {
        tier: "Tier 1",
        damage: ["One-Hand Damage: 10 to 12"],
        requirement: ["Required Level: 8", "Required Strength: 58 to 72", "Item Level: 12", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "+1 to All Skills",
          "+(6 to 10)% to Physical/Magic Spell Damage",
          "+(11 to 20) to Energy",
          "Physical Resist 1%",
          "2% Reanimate as: Dark Templar",
          "-(1 to 20)% Magic Find",
          "Requirements -(1 to 20)%",
          "Socketed (2)",
        ],
      },
      {
        tier: "Tier 2",
        damage: ["One-Hand Damage: 18 to 21"],
        requirement: ["Required Level: 26", "Required Strength: 77 to 97", "Item Level: 29", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "+(1 to 2) to All Skills",
          "+(16 to 20)% to Physical/Magic Spell Damage",
          "+(21 to 30) to Energy",
          "Physical Resist 2%",
          "3% Reanimate as: Dark Templar",
          "-(11 to 30)% Magic Find",
          "Requirements -(11 to 30)%",
          "Socketed (4)",
        ],
      },
      {
        tier: "Tier 3",
        damage: ["One-Hand Damage: 28 to 33"],
        requirement: ["Required Level: 45", "Required Strength: 140 to 181", "Item Level: 50", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "+2 to All Skills",
          "+(21 to 25)% to Physical/Magic Spell Damage",
          "+(31 to 40) to Energy",
          "Physical Resist 3%",
          "4% Reanimate as: Dark Templar",
          "-(16 to 35)% Magic Find",
          "Requirements -(16 to 35)%",
          "Socketed (5)",
        ],
      },
      {
        tier: "Tier 4",
        damage: ["One-Hand Damage: 33 to 39"],
        requirement: ["Required Level: 54", "Required Strength: 256 to 337", "Item Level: 85", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "+3 to All Skills",
          "+(31 to 35)% to Physical/Magic Spell Damage",
          "+(41 to 50) to Energy",
          "Physical Resist 4%",
          "5% Reanimate as: Dark Templar",
          "-(21 to 40)% Magic Find",
          "Requirements -(21 to 40)%",
          "Socketed (6)",
        ],
      },
    ],
  },
  {
    id: 6,
    name: "Lachdanan&apos;s Avenger (War Sword)",
    img: "https://docs.median-xl.com/images/baseitems/invwsd.jpg",
    info: [
      {
        tier: "Tier 1",
        damage: ["One-Hand Damage: (17 - 19) to (20 - 23)"],
        requirement: ["Required Strength: 85", "Item Level: 18", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "4% Chance to cast level 3 Spike Nova on Melee Attack",
          "+1 to Paladin Skill Levels",
          "+(61 to 80)% Enhanced Damage",
          "+(101 to 125)% Damage to Demons",
          "+(101 to 125)% Damage to Undead",
          "(1 to 2)% Chance of Crushing Blow",
          "+(16 to 25) to Strength",
          "+(16 to 25) to Dexterity",
          "Elemental Resists +(11 to 15)%",
          "Socketed (1)",
        ],
      },
      {
        tier: "Tier 2",
        damage: ["One-Hand Damage: (38 - 41) to (46 - 50)"],
        requirement: ["Required Strength: 125", "Item Level: 34", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "5% Chance to cast level 11 Spike Nova on Melee Attack",
          "+(1 to 2) to Paladin Skill Levels",
          "+(101 to 120)% Enhanced Damage",
          "+(176 to 200)% Damage to Demons",
          "+(176 to 200)% Damage to Undead",
          "(3 to 4)% Chance of Crushing Blow",
          "+(36 to 45) to Strength",
          "+(36 to 45) to Dexterity",
          "Elemental Resists +(21 to 25)%",
          "Socketed (2)",
        ],
      },
      {
        tier: "Tier 3",
        damage: ["One-Hand Damage: (72 - 78) to (84 - 91)"],
        requirement: ["Required Strength: 244", "Item Level: 54", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "6% Chance to cast level 19 Spike Nova on Melee Attack",
          "+(2 to 3) to Paladin Skill Levels",
          "+(141 to 160)% Enhanced Damage",
          "+(226 to 250)% Damage to Demons",
          "+(226 to 250)% Damage to Undead",
          "(5 to 6)% Chance of Crushing Blow",
          "+(56 to 65) to Strength",
          "+(56 to 65) to Dexterity",
          "Elemental Resists +(31 to 35)%",
          "Socketed (3)",
        ],
      },
      {
        tier: "Tier 4",
        damage: ["One-Hand Damage: (98 - 105) to (118 - 126)"],
        requirement: ["Required Strength: 481", "Item Level: 90", "Strength Damage Bonus: (0.18 per Strength)%"],
        attribute: [
          "7% Chance to cast level 23 Spike Nova on Melee Attack",
          "+3 to Paladin Skill Levels",
          "+(181 to 200)% Enhanced Damage",
          "+(276 to 300)% Damage to Demons",
          "+(276 to 300)% Damage to Undead",
          "(7 to 8)% Chance of Crushing Blow",
          "+(66 to 75) to Strength",
          "+(66 to 75) to Dexterity",
          "Elemental Resists +(36 to 40)%",
          "Socketed (3)",
        ],
      },
    ],
  },
];
