export const twoHandSword = [
  {
    id: 7,
    name: "The Overlord (Two-Handed Sword)",
    img: "https://docs.median-xl.com/images/baseitems/inv2hs.jpg",
    info: [
      {
        tier: "Tier 1",
        damage: ["One-Hand Damage: (8 - 9) to (19 - 23)", "Two-Hand Damage: (8 - 9) to (24 - 29)"],
        requirement: ["Required Strength: 25", "Item Level: 1", "Strength Damage Bonus: (0.26 per Strength)%"],
        attribute: [
          "+2 to Amazon Skill Levels",
          "+(61 to 90)% Enhanced Damage",
          "+(8 to 10) to Maximum Damage",
          "+(2 to 3) to Wyrd",
          "Slow Target (7 to 10)%",
          "(2 to 5)% to Strength",
          "(21 to 25)% Chance of Uninterruptable Attack",
          "Socketed (2)",
        ],
      },
      {
        tier: "Tier 2",
        damage: ["One-Hand Damage: (17 - 18) to (35 - 41)", "Two-Hand Damage: (24 - 27) to (40 - 47)"],
        requirement: ["Required Strength: 48", "Item Level: 20", "Strength Damage Bonus: (0.26 per Strength)%"],
        attribute: [
          "+3 to Amazon Skill Levels",
          "+(91 to 110)% Enhanced Damage",
          "+(16 to 20) to Maximum Damage",
          "+(5 to 6) to Wyrd",
          "Slow Target (11 to 15)%",
          "(10 to 13)% to Strength",
          "(31 to 35)% Chance of Uninterruptable Attack",
          "Socketed (3)",
        ],
      },
      {
        tier: "Tier 3",
        damage: ["One-Hand Damage: (29 - 32) to (59 - 66)", "Two-Hand Damage: (44 - 48) to (72 - 80)"],
        requirement: ["Required Strength: 104", "Item Level: 41", "Strength Damage Bonus: (0.26 per Strength)%"],
        attribute: [
          "+5 to Amazon Skill Levels",
          "+(111 to 130)% Enhanced Damage",
          "+(26 to 30) to Maximum Damage",
          "+(8 to 9) to Wyrd",
          "Slow Target (16 to 20)%",
          "(18 to 21)% to Strength",
          "(41 to 45)% Chance of Uninterruptable Attack",
          "Socketed (4)",
        ],
      },
      {
        tier: "Tier 4",
        damage: ["One-Hand Damage: (39 - 42) to (82 - 90)", "Two-Hand Damage: (57 - 62) to (98 - 107)"],
        requirement: ["Required Strength: 212", "Item Level: 73", "Strength Damage Bonus: (0.26 per Strength)%"],
        attribute: [
          "+7 to Amazon Skill Levels",
          "+(131 to 150)% Enhanced Damage",
          "+(36 to 40) to Maximum Damage",
          "+(12 to 13) to Wyrd",
          "Slow Target (21 to 25)%",
          "(22 to 25)% to Strength",
          "(46 to 50)% Chance of Uninterruptable Attack",
          "Socketed (4)",
        ],
      },
    ],
  },
  {
    id: 8,
    name: "Jared&apos;s Fragmentor (Claymore)",
    img: "https://docs.median-xl.com/images/baseitems/invclm.jpg",
    info: [
      {
        tier: "Tier 1",
        damage: ["One-Hand Damage: (8 - 9) to (13 - 17)", "Two-Hand Damage: (12 - 14) to (18 - 22)"],
        requirement: ["Required Strength: 41", "Item Level: 4", "Strength Damage Bonus: (0.26 per Strength)%"],
        attribute: [
          "5% Chance to cast level 4 Spike Nova on Melee Attack",
          "+(41 to 60)% Enhanced Damage",
          "+(4 to 6) to Maximum Damage",
          "(2 to 3)% Chance of Crushing Blow",
          "+(21 to 30) Life on Attack",
          "Socketed (2)",
        ],
      },
      {
        tier: "Tier 2",
        damage: ["One-Hand Damage: (20 - 22) to (30 - 36)", "Two-Hand Damage: (30 - 34) to (40 - 48)"],
        requirement: ["Required Strength: 69", "Item Level: 23", "Strength Damage Bonus: (0.26 per Strength)%"],
        attribute: [
          "10% Chance to cast level 8 Spike Nova on Melee Attack",
          "+(71 to 90)% Enhanced Damage",
          "+(8 to 12) to Maximum Damage",
          "(4 to 6)% Chance of Crushing Blow",
          "+(46 to 60) Life on Attack",
          "Socketed (3)",
        ],
      },
      {
        tier: "Tier 3",
        damage: ["One-Hand Damage: (36 - 39) to (58 - 70)", "Two-Hand Damage: (58 - 63) to (80 - 94)"],
        requirement: ["Required Strength: 142", "Item Level: 43", "Strength Damage Bonus: (0.26 per Strength)%"],
        attribute: [
          "15% Chance to cast level 12 Spike Nova on Melee Attack",
          "+(101 to 120)% Enhanced Damage",
          "+(16 to 24) to Maximum Damage",
          "(7 to 9)% Chance of Crushing Blow",
          "+(71 to 90) Life on Attack",
          "Socketed (4)",
        ],
      },
      {
        tier: "Tier 4",
        damage: ["One-Hand Damage: (48 - 52) to (89 - 110)", "Two-Hand Damage: (83 - 90) to (117 - 140)"],
        requirement: ["Required Strength: 283", "Item Level: 78", "Strength Damage Bonus: (0.26 per Strength)%"],
        attribute: [
          "20% Chance to cast level 14 Spike Nova on Melee Attack",
          "+(131 to 150)% Enhanced Damage",
          "+(32 to 48) to Maximum Damage",
          "(10 to 12)% Chance of Crushing Blow",
          "+(91 to 120) Life on Attack",
          "Socketed (4)",
        ],
      },
    ],
  },
  {
    id: 9,
    name: "Hellreaper (Giant Sword)",
    img: "https://docs.median-xl.com/images/baseitems/invgis.jpg",
    info: [
      {
        tier: "Tier 1",
        damage: ["One-Hand Damage: (12 - 14) to (14 - 16)", "Two-Hand Damage: (20 - 23) to (20 - 23)"],
        requirement: ["Required Strength: 57", "Item Level: 7", "Strength Damage Bonus: (0.26 per Strength)%"],
        attribute: [
          "5% Attack Speed",
          "+(61 to 80)% Enhanced Damage",
          "(3 to 5)% Life stolen per Hit",
          "+(2 to 5) to Iron Spiral",
          "Enhanced Weapon Damage +(16 to 25)%",
          "+(21 to 50) Defense",
          "Maximum Life (3 to 5)%",
          "Socketed (2)",
        ],
      },
      {
        tier: "Tier 2",
        damage: ["One-Hand Damage: (26 - 29) to (32 - 35)", "Two-Hand Damage: (45 - 50) to (49 - 54)"],
        requirement: ["Required Strength: 89", "Item Level: 25", "Strength Damage Bonus: (0.26 per Strength)%"],
        attribute: [
          "15% Attack Speed",
          "+(91 to 110)% Enhanced Damage",
          "(9 to 11)% Life stolen per Hit",
          "+(6 to 9) to Iron Spiral",
          "Enhanced Weapon Damage +(36 to 45)%",
          "+(81 to 110) Defense",
          "Maximum Life (9 to 11)%",
          "Socketed (3)",
        ],
      },
      {
        tier: "Tier 3",
        damage: ["One-Hand Damage: (48 - 55) to (57 - 65)", "Two-Hand Damage: (83 - 95) to (88 - 100)"],
        requirement: ["Required Strength: 179", "Item Level: 46", "Strength Damage Bonus: (0.26 per Strength)%"],
        attribute: [
          "25% Attack Speed",
          "+(121 to 150)% Enhanced Damage",
          "(15 to 17)% Life stolen per Hit",
          "+(10 to 14) to Iron Spiral",
          "Enhanced Weapon Damage +(56 to 65)%",
          "+(141 to 170) Defense",
          "Maximum Life (15 to 17)%",
          "Socketed (4)",
        ],
      },
      {
        tier: "Tier 4",
        damage: ["One-Hand Damage: (67 - 78) to (80 - 93)", "Two-Hand Damage: (117 - 135) to (125 - 144)"],
        requirement: ["Required Strength: 355", "Item Level: 81", "Strength Damage Bonus: (0.26 per Strength)%"],
        attribute: [
          "30% Attack Speed",
          "+(161 to 200)% Enhanced Damage",
          "(18 to 20)% Life stolen per Hit",
          "+(15 to 20) to Iron Spiral",
          "Enhanced Weapon Damage +(66 to 75)%",
          "+(171 to 200) Defense",
          "Maximum Life (18 to 20)%",
          "Socketed (4)",
        ],
      },
    ],
  },
  {
    id: 10,
    name: "Addertongue (Bastard Sword)",
    img: "https://docs.median-xl.com/images/baseitems/invbsw.jpg",
    info: [
      {
        tier: "Tier 1",
        damage: ["One-Hand Damage: 9 to 11", "Two-Hand Damage: 16 to 17"],
        requirement: ["Required Level: 6", "Required Strength: 73", "Item Level: 9", "Strength Damage Bonus: (0.26 per Strength)%"],
        attribute: [
          "+1 to Paladin Skill Levels",
          "+(11 to 15)% to Cold Spell Damage",
          "-3% to Enemy Cold Resistance",
          "+(1 to 2) to Winter Avatar",
          "(3 to 5)% to Strength",
          "(3 to 5)% to Energy",
          "Total Character Defense (3 to 5)%",
          "Socketed (2)",
        ],
      },
      {
        tier: "Tier 2",
        damage: ["One-Hand Damage: 17 to 20", "Two-Hand Damage: 30 to 32"],
        requirement: ["Required Level: 24", "Required Strength: 110", "Item Level: 27", "Strength Damage Bonus: (0.26 per Strength)%"],
        attribute: [
          "+2 to Paladin Skill Levels",
          "+(16 to 20)% to Cold Spell Damage",
          "-6% to Enemy Cold Resistance",
          "+(3 to 5) to Winter Avatar",
          "(9 to 11)% to Strength",
          "(9 to 11)% to Energy",
          "Total Character Defense (9 to 11)%",
          "Socketed (3)",
        ],
      },
      {
        tier: "Tier 3",
        damage: ["One-Hand Damage: 26 to 31", "Two-Hand Damage: 46 to 49"],
        requirement: ["Required Level: 43", "Required Strength: 216", "Item Level: 48", "Strength Damage Bonus: (0.26 per Strength)%"],
        attribute: [
          "+3 to Paladin Skill Levels",
          "+(21 to 25)% to Cold Spell Damage",
          "-9% to Enemy Cold Resistance",
          "+(6 to 7) to Winter Avatar",
          "(15 to 17)% to Strength",
          "(15 to 17)% to Energy",
          "Total Character Defense (15 to 17)%",
          "Socketed (4)",
        ],
      },
      {
        tier: "Tier 4",
        damage: ["One-Hand Damage: 31 to 37", "Two-Hand Damage: 56 to 59"],
        requirement: ["Required Level: 52", "Required Strength: 427", "Item Level: 82", "Strength Damage Bonus: (0.26 per Strength)%"],
        attribute: [
          "+4 to Paladin Skill Levels",
          "+(26 to 30)% to Cold Spell Damage",
          "-12% to Enemy Cold Resistance",
          "+(9 to 10) to Winter Avatar",
          "(18 to 20)% to Strength",
          "(18 to 20)% to Energy",
          "Total Character Defense (18 to 20)%",
          "Socketed (4)",
        ],
      },
    ],
  },
  {
    id: 11,
    name: "Frostbringer (Flamberge)",
    img: "https://docs.median-xl.com/images/baseitems/invflb.jpg",
    info: [
      {
        tier: "Tier 1",
        damage: ["One-Hand Damage: (12 - 14) to (23 - 30)", "Two-Hand Damage: (22 - 25) to (32 - 41)"],
        requirement: ["Required Strength: 89", "Item Level: 11", "Strength Damage Bonus: (0.26 per Strength)%"],
        attribute: [
          "25% Chance to cast level 5 Ice Lance on Melee Attack",
          "+1 to All Skills",
          "+(18 to 35)% Enhanced Damage",
          "+(8 to 13) to Maximum Damage",
          "+(11 to 20)% to Cold Spell Damage",
          "Cold Resist +(21 to 25)%",
          "(3 to 5)% Chance of Uninterruptable Attack",
          "Socketed (2)",
        ],
      },
      {
        tier: "Tier 2",
        damage: ["One-Hand Damage: (28 - 32) to (52 - 61)", "Two-Hand Damage: (54 - 60) to (75 - 87)"],
        requirement: ["Required Strength: 130", "Item Level: 29", "Strength Damage Bonus: (0.26 per Strength)%"],
        attribute: [
          "35% Chance to cast level 15 Ice Lance on Melee Attack",
          "+2 to All Skills",
          "+(52 to 69)% Enhanced Damage",
          "+(18 to 23) to Maximum Damage",
          "+(21 to 30)% to Cold Spell Damage",
          "Cold Resist +(31 to 35)%",
          "(9 to 11)% Chance of Uninterruptable Attack",
          "Socketed (4)",
        ],
      },
      {
        tier: "Tier 3",
        damage: ["One-Hand Damage: (56 - 60) to (95 - 106)", "Two-Hand Damage: (102 - 111) to (136 - 150)"],
        requirement: ["Required Strength: 253", "Item Level: 49", "Strength Damage Bonus: (0.26 per Strength)%"],
        attribute: [
          "45% Chance to cast level 25 Ice Lance on Melee Attack",
          "+(2 to 3) to All Skills",
          "+(87 to 103)% Enhanced Damage",
          "+(28 to 33) to Maximum Damage",
          "+(31 to 40)% to Cold Spell Damage",
          "Cold Resist +(41 to 45)%",
          "(15 to 17)% Chance of Uninterruptable Attack",
          "Socketed (5)",
        ],
      },
      {
        tier: "Tier 4",
        damage: ["One-Hand Damage: (71 - 77) to (118 - 130)", "Two-Hand Damage: (132 - 143) to (173 - 189)"],
        requirement: ["Required Strength: 499", "Item Level: 85", "Strength Damage Bonus: (0.26 per Strength)%"],
        attribute: [
          "50% Chance to cast level 30 Ice Lance on Melee Attack",
          "+3 to All Skills",
          "+(104 to 120)% Enhanced Damage",
          "+(33 to 38) to Maximum Damage",
          "+(41 to 50)% to Cold Spell Damage",
          "Cold Resist +(46 to 50)%",
          "(18 to 20)% Chance of Uninterruptable Attack",
          "Socketed (6)",
        ],
      },
    ],
  },
  {
    id: 12,
    name: "The Dao of Xiansai (Great Sword)",
    img: "https://docs.median-xl.com/images/baseitems/invgsd.jpg",
    info: [
      {
        tier: "Tier 1",
        damage: ["One-Hand Damage: (14 - 16) to (32 - 45)", "Two-Hand Damage: (25 - 29) to (42 - 56)"],
        requirement: ["Required Strength: 105", "Item Level: 17", "Strength Damage Bonus: (0.26 per Strength)%"],
        attribute: [
          "+1 to All Skills",
          "15% Attack Speed",
          "15% Hit Recovery",
          "+(18 to 35)% Enhanced Damage",
          "+(15 to 25) to Maximum Damage",
          "(51 to 75)% Bonus to Attack Rating",
          "+(101 to 150) Defense",
          "+1% to Experience Gained",
          "Socketed (2)",
        ],
      },
      {
        tier: "Tier 2",
        damage: ["One-Hand Damage: (31 - 35) to (70 - 83)", "Two-Hand Damage: (60 - 67) to (96 - 112)"],
        requirement: ["Required Strength: 151", "Item Level: 33", "Strength Damage Bonus: (0.26 per Strength)%"],
        attribute: [
          "+2 to All Skills",
          "25% Attack Speed",
          "25% Hit Recovery",
          "+(52 to 69)% Enhanced Damage",
          "+(31 to 40) to Maximum Damage",
          "(101 to 125)% Bonus to Attack Rating",
          "+(201 to 250) Defense",
          "+2% to Experience Gained",
          "Socketed (4)",
        ],
      },
      {
        tier: "Tier 3",
        damage: ["One-Hand Damage: (59 - 64) to (123 - 149)", "Two-Hand Damage: (114 - 123) to (172 - 201)"],
        requirement: ["Required Strength: 291", "Item Level: 54", "Strength Damage Bonus: (0.26 per Strength)%"],
        attribute: [
          "+3 to All Skills",
          "35% Attack Speed",
          "35% Hit Recovery",
          "+(87 to 103)% Enhanced Damage",
          "+(51 to 70) to Maximum Damage",
          "(151 to 175)% Bonus to Attack Rating",
          "+(301 to 350) Defense",
          "+2% to Experience Gained",
          "Socketed (5)",
        ],
      },
      {
        tier: "Tier 4",
        damage: ["One-Hand Damage: (77 - 83) to (166 - 193)", "Two-Hand Damage: (148 - 160) to (228 - 259)"],
        requirement: ["Required Strength: 570", "Item Level: 90", "Strength Damage Bonus: (0.26 per Strength)%"],
        attribute: [
          "+4 to All Skills",
          "40% Attack Speed",
          "40% Hit Recovery",
          "+(104 to 120)% Enhanced Damage",
          "+(71 to 90) to Maximum Damage",
          "(176 to 200)% Bonus to Attack Rating",
          "+(351 to 400) Defense",
          "+3% to Experience Gained",
          "Socketed (6)",
        ],
      },
    ],
  },
];
